//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 10:45:43 PM CEST 
//


package com.project.Businessinformatics.model.xml;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clearingAndSettlementItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clearingAndSettlementItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://com/xsdSchemas/types}str50num"/>
 *         &lt;element name="originator" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="paymentPurpose" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="reciever" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="statementDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="originatorAccountNumber" type="{http://com/xsdSchemas/types}accountNumber"/>
 *         &lt;element name="chargeModel" type="{http://com/xsdSchemas/types}ordinate2"/>
 *         &lt;element name="chargeDialNumber" type="{http://com/xsdSchemas/types}str20num"/>
 *         &lt;element name="recieverAccountNumber" type="{http://com/xsdSchemas/types}accountNumber"/>
 *         &lt;element name="clearanceModel" type="{http://com/xsdSchemas/types}ordinate2"/>
 *         &lt;element name="clearanceDialNumber" type="{http://com/xsdSchemas/types}str20num"/>
 *         &lt;element name="amount" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="currency" type="{http://com/xsdSchemas/types}str3currency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clearingAndSettlementItem", propOrder = {
    "requestId",
    "originator",
    "paymentPurpose",
    "reciever",
    "statementDate",
    "originatorAccountNumber",
    "chargeModel",
    "chargeDialNumber",
    "recieverAccountNumber",
    "clearanceModel",
    "clearanceDialNumber",
    "amount",
    "currency"
})
@XmlRootElement(name = "stetementItem")
public class ClearingAndSettlementItem {
	
	@XmlTransient
	@Id
	@GeneratedValue
	private Long id;

	@Column(nullable = false)
    @XmlElement(required = true)
    @Size(max = 50)
    protected String requestId;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 255)
    protected String originator;
  
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 255)
    protected String paymentPurpose;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 255)
    protected String reciever;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Column(nullable = false)
    protected String statementDate;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 18)
    protected String originatorAccountNumber;
    
    @XmlElement(required =true)
    @Column(nullable = true)
    protected short chargeModel;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 20)
    protected String chargeDialNumber;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 18)
    protected String recieverAccountNumber;
    
    @XmlElement(required =true)
    @Column(nullable = true)
    protected short clearanceModel;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 20)
    protected String clearanceDialNumber;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Digits(integer = 17, fraction = 2)
    protected BigDecimal amount;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(min = 3, max = 3)
    protected String currency;
    
    @XmlTransient
    @ManyToOne(optional = false)
    private Mt102Request mt102Request;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginator(String value) {
        this.originator = value;
    }

    /**
     * Gets the value of the paymentPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentPurpose() {
        return paymentPurpose;
    }

    /**
     * Sets the value of the paymentPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentPurpose(String value) {
        this.paymentPurpose = value;
    }

    /**
     * Gets the value of the reciever property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReciever() {
        return reciever;
    }

    /**
     * Sets the value of the reciever property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReciever(String value) {
        this.reciever = value;
    }

    /**
     * Gets the value of the statementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */

    /**
     * Sets the value of the statementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */

    /**
     * Gets the value of the originatorAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorAccountNumber() {
        return originatorAccountNumber;
    }

    /**
     * Sets the value of the originatorAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorAccountNumber(String value) {
        this.originatorAccountNumber = value;
    }

    /**
     * Gets the value of the chargeModel property.
     * 
     */
    public short getChargeModel() {
        return chargeModel;
    }

    /**
     * Sets the value of the chargeModel property.
     * 
     */
    public void setChargeModel(short value) {
        this.chargeModel = value;
    }

    /**
     * Gets the value of the chargeDialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeDialNumber() {
        return chargeDialNumber;
    }

    /**
     * Sets the value of the chargeDialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeDialNumber(String value) {
        this.chargeDialNumber = value;
    }

    /**
     * Gets the value of the recieverAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecieverAccountNumber() {
        return recieverAccountNumber;
    }

    /**
     * Sets the value of the recieverAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecieverAccountNumber(String value) {
        this.recieverAccountNumber = value;
    }

    /**
     * Gets the value of the clearanceModel property.
     * 
     */
    public short getClearanceModel() {
        return clearanceModel;
    }

    /**
     * Sets the value of the clearanceModel property.
     * 
     */
    public void setClearanceModel(short value) {
        this.clearanceModel = value;
    }

    /**
     * Gets the value of the clearanceDialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearanceDialNumber() {
        return clearanceDialNumber;
    }

    /**
     * Sets the value of the clearanceDialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearanceDialNumber(String value) {
        this.clearanceDialNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

	public Long getId() {
		return id;
	}

	public Mt102Request getMt102Request() {
		return mt102Request;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	public void setMt102Request(Mt102Request mt102Request) {
		this.mt102Request = mt102Request;
	}

	public String getStatementDate() {
		return statementDate;
	}

	public void setStatementDate(String statementDate) {
		this.statementDate = statementDate;
	}

}
