//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 10:45:43 PM CEST 
//


package com.project.Businessinformatics.model.xml;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageId" type="{http://com/xsdSchemas/types}str50num"/>
 *         &lt;element name="originatorBankSwiftCode" type="{http://com/xsdSchemas/types}swift"/>
 *         &lt;element name="originatorBankTransactionAccount" type="{http://com/xsdSchemas/types}accountNumber"/>
 *         &lt;element name="recieverBankSwiftCode" type="{http://com/xsdSchemas/types}swift"/>
 *         &lt;element name="recieverBankTransactionAccount" type="{http://com/xsdSchemas/types}accountNumber"/>
 *         &lt;element name="amount" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="currency" type="{http://com/xsdSchemas/types}str3currency"/>
 *         &lt;element name="currencyDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="statementItems" type="{http://com/xsdSchemas/clearingAndSettlementItem}clearingAndSettlementItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageId",
    "originatorBankSwiftCode",
    "originatorBankTransactionAccount",
    "recieverBankSwiftCode",
    "recieverBankTransactionAccount",
    "amount",
    "currency",
    "currencyDate",
    "date",
    "statementItems"
})
@XmlRootElement(name = "mt102Request")
@Entity
public class Mt102Request {
	
	@XmlTransient
	@Id
	@GeneratedValue
	private Long id;
	
	@Column(nullable = false)
	@XmlTransient
	private boolean processed;

    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 50)
    protected String messageId;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 8)
    protected String originatorBankSwiftCode;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 18)
    protected String originatorBankTransactionAccount;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 8)
    protected String recieverBankSwiftCode;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(max = 18)
    protected String recieverBankTransactionAccount;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Digits(integer=17, fraction=2)
    protected BigDecimal amount;
    
    @XmlElement(required = true)
    @Column(nullable = false)
    @Size(min = 3, max = 3)
    protected String currency;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Column(nullable = false)
    protected String currencyDate; 
  
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Column(nullable = false)
    protected String date;
    
    @XmlElement(required = true)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "mt102Request", orphanRemoval = true, targetEntity = ClearingAndSettlementItem.class)
    protected Set<ClearingAndSettlementItem> statementItems;
    
    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the originatorBankSwiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorBankSwiftCode() {
        return originatorBankSwiftCode;
    }

    /**
     * Sets the value of the originatorBankSwiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorBankSwiftCode(String value) {
        this.originatorBankSwiftCode = value;
    }

    /**
     * Gets the value of the originatorBankTransactionAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorBankTransactionAccount() {
        return originatorBankTransactionAccount;
    }

    /**
     * Sets the value of the originatorBankTransactionAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorBankTransactionAccount(String value) {
        this.originatorBankTransactionAccount = value;
    }

    /**
     * Gets the value of the recieverBankSwiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecieverBankSwiftCode() {
        return recieverBankSwiftCode;
    }

    /**
     * Sets the value of the recieverBankSwiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecieverBankSwiftCode(String value) {
        this.recieverBankSwiftCode = value;
    }

    /**
     * Gets the value of the recieverBankTransactionAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecieverBankTransactionAccount() {
        return recieverBankTransactionAccount;
    }

    /**
     * Sets the value of the recieverBankTransactionAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecieverBankTransactionAccount(String value) {
        this.recieverBankTransactionAccount = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the currencyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    

    /**
     * Sets the value of the currencyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
   

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    

    /**
     * Gets the value of the statementItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClearingAndSettlementItem }
     * 
     * 
     */
    @JsonIgnore
    public Set<ClearingAndSettlementItem> getStatementItems() {
        if (statementItems == null) {
            statementItems = new HashSet<ClearingAndSettlementItem>();
        }
        return this.statementItems;
    }
    
    
    
	public void setId(Long id) {
		this.id = id;
	}

	public void setStatementItems(Set<ClearingAndSettlementItem> statementItems) {
		this.statementItems = statementItems;
	}

	public Long getId() {
		return id;
	}

	public boolean isProcessed() {
		return processed;
	}

	public void setProcessed(boolean processed) {
		this.processed = processed;
	}

	public String getCurrencyDate() {
		return currencyDate;
	}

	public void setCurrencyDate(String currencyDate) {
		this.currencyDate = currencyDate;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}
	
}
